#!/usr/bin/env node
// Renders the PRODUCTION media server (LiveKit) config from environment values.
//
//   LIVEKIT_API_KEY=... LIVEKIT_API_SECRET=... node render-config.mjs > livekit.generated.yaml
//
// The repository's livekit.yaml is for development only: it holds a public key and
// secret and pins the server to 127.0.0.1. Production settings are generated here
// at deploy time from secrets and are never committed. Anything that would make
// the server unsafe or unreachable is refused, listing every problem at once and
// printing nothing to stdout, so a half-made config is never saved by `> file`.
//
// Values, all from the environment:
//   LIVEKIT_API_KEY, LIVEKIT_API_SECRET   required; not the development ones; secret >= 32 chars
//   LIVEKIT_NODE_IP                       optional public IPv4. If unset the server discovers its own
//   LIVEKIT_TURN_DOMAIN + LIVEKIT_TURN_CERT_FILE + LIVEKIT_TURN_KEY_FILE
//                                         optional; turns on TURN over TLS (port 5349)

import { fileURLToPath } from "node:url";

const DEV_KEY = "devkey";
const DEV_SECRET = "dev-livekit-secret-change-me-32chars-min";

export class ConfigError extends Error {
  constructor(problems) {
    super(`Refusing to write the media server config:\n  - ${problems.join("\n  - ")}`);
    this.name = "ConfigError";
    this.problems = problems;
  }
}

/** A public IPv4 address: four numbers 0-255 that are not loopback, unspecified,
 *  link-local or in a private range (10/8, 172.16/12, 192.168/16). A browser on
 *  another network cannot reach any of those, which is exactly how the dev server
 *  ended up advertising its container address. */
function isPublicIPv4(value) {
  const match = /^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/.exec(value);
  if (!match) return false;
  const [a, b, c, d] = match.slice(1).map(Number);
  if ([a, b, c, d].some((n) => n > 255)) return false;
  if (a === 0 || a === 127 || a === 10) return false;
  if (a === 169 && b === 254) return false;
  if (a === 172 && b >= 16 && b <= 31) return false;
  if (a === 192 && b === 168) return false;
  return true;
}

const q = (value) => JSON.stringify(value); // a JSON string is a valid, safely quoted YAML string

/** Returns the config text, or throws ConfigError listing every problem. */
export function renderLiveKitConfig(env) {
  const problems = [];
  const key = env.LIVEKIT_API_KEY?.trim();
  const secret = env.LIVEKIT_API_SECRET?.trim();
  const nodeIp = env.LIVEKIT_NODE_IP?.trim();
  const turnDomain = env.LIVEKIT_TURN_DOMAIN?.trim();
  const turnCert = env.LIVEKIT_TURN_CERT_FILE?.trim();
  const turnKey = env.LIVEKIT_TURN_KEY_FILE?.trim();

  if (!key) problems.push("LIVEKIT_API_KEY is missing.");
  else if (key === DEV_KEY) problems.push("LIVEKIT_API_KEY is the public development key.");
  else if (/\s/.test(key) || key.length < 8) problems.push("LIVEKIT_API_KEY must be at least 8 characters with no spaces.");

  if (!secret) problems.push("LIVEKIT_API_SECRET is missing.");
  else if (secret === DEV_SECRET) problems.push("LIVEKIT_API_SECRET is the public development secret.");
  else if (secret.length < 32) problems.push("LIVEKIT_API_SECRET must be at least 32 characters.");

  if (nodeIp !== undefined && nodeIp !== "" && !isPublicIPv4(nodeIp)) {
    problems.push("LIVEKIT_NODE_IP must be a public IPv4 address (not localhost, 127.x, 0.0.0.0, a private range, or a container address).");
  }

  if (turnDomain) {
    if (!turnCert) problems.push("LIVEKIT_TURN_CERT_FILE is required when LIVEKIT_TURN_DOMAIN is set.");
    if (!turnKey) problems.push("LIVEKIT_TURN_KEY_FILE is required when LIVEKIT_TURN_DOMAIN is set.");
  }

  if (problems.length > 0) throw new ConfigError(problems);

  const lines = [
    "# GENERATED by deploy/livekit/render-config.mjs at deploy time. Contains a secret:",
    "# keep it out of git, readable by the media server only (chmod 600).",
    `keys:`,
    `  ${q(key)}: ${q(secret)}`,
    "",
    "port: 7880",
    "",
    "rtc:",
    "  tcp_port: 7881",
    "  port_range_start: 50000",
    "  port_range_end: 60000",
    ...(nodeIp ? [`  node_ip: ${q(nodeIp)}`] : ["  use_external_ip: true"]),
  ];

  if (turnDomain) {
    lines.push("", "turn:", "  enabled: true", `  domain: ${q(turnDomain)}`, "  tls_port: 5349", `  cert_file: ${q(turnCert)}`, `  key_file: ${q(turnKey)}`);
  }

  lines.push("", "logging:", "  level: info", "");
  return lines.join("\n");
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  try {
    process.stdout.write(renderLiveKitConfig(process.env));
  } catch (error) {
    if (error instanceof ConfigError) {
      process.stderr.write(`${error.message}\n`);
      process.exit(1);
    }
    throw error;
  }
}
